sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: lfGpasU5oBbaVpZz0eKIZ9uv1kx0ys9YNpKI/5S9TRFveVXWD7JmGscF9lx3me7pUVDAhk8+WUMiKq0CqFE5N24U5flhcMI/A3xla+Yg0LYBNGSs5+3T2dz7V3KlUNATZ/uSw177/V2S8Ev9kA1E0Tr/7PuUErfcWpyAdrBUa5val+9s9PIduo+eVE28QcEfRR1Y+hURtOpzUvva7gXqk29iwcRdzFJ5vEg0/jnsrn2Ny6QgFD2VjcG71hPZI4LRUT0DyjaabdUhNqlgjbmPQFTwBkI6EJuLoJmprfqDI/7JuoVaABsIa05OuD+/y3vYskt8KBJQsQiumrnCxn99ZVlpM2ZBDGsU7YtyFUuApv8QFxsrqVcdgqZRSgHyUjALKVaP5mz7+eOJjxanrJqALuW1DiUoI6FTuNar9uoo/8E3nhIBELLnBJpuUPRZwGyZVBs4FsDirvDpcqu2HUOFQ7KJmV5q5dqgAL445TVbqxQKHsrf6//uXj+q+c2kunRorqee+E8e1kl/wwWUs54FeO93DaTZkdVa2sbb0rJO6QYq7dgdO90ZsKWc057MGZerAVNnKfUXl/yVjeduacjcU7dXPs50BIDUjffhK+QVi1lHRdMte8FGVSLQixqpaPSCsNPlzFrrIrJ4Ld/OQ64mHvxBDSQgaYO7RGajYsfwFo0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/La-Grenadiere_1428
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy